FROM python:3.11 as python-base
RUN mkdir starnavi_social
WORKDIR  /starnavi_social
COPY /pyproject.toml /starnavi_social
RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install 
COPY . .
CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]