
@base=http://127.0.0.1:8000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwidHlwZSI6ImFjY2VzcyIsImV4cCI6MTcwNjU2OTUwNX0.RVjstJALxtt7EpoprUhAh6UmMTn_d7p2gequMJu09yo

### register new customer
POST {{base}}/auth/signup
Content-Type: application/json

{
  "firstname": "string",
  "lastname": "string",
  "email": "{{$guid}}@example.com",
  "phoneNum": "{{$guid}}",
  "birthday": "2010-01-25",
  "username": "{{$guid}}",
  "password": "asfnksadfnkasf",
  "password_confirmation": "asfnksadfnkasf",
  "subscribed_for_newsletter": false
}

### login
POST {{base}}/auth/signin
Content-Type: application/json

{
  "email": "5f0b807d-aef6-486e-aeaf-15de78627640@example.com",
  "password": "asfnksadfnkasf"
}


### post create
POST {{base}}/post/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "string",
  "description": "string"
}

### post like
POST {{base}}/post/1912391/like
Content-Type: application/json
Authorization: Bearer {{token}}


### post dislike
POST {{base}}/post/1231323121/dislike
Content-Type: application/json
Authorization: Bearer {{token}}

### get activity by user
GET {{base}}/user_info/activity
Content-Type: application/json
Authorization: Bearer {{token}}